# kind: Deployment
# 컨트롤러가 이 템플릿을 기반으로 Deployment 리소스를 생성합니다.
# Deployment는 Pod의 실행을 보장하고, Pod가 비정상 종료되면 자동으로 재시작합니다.
apiVersion: apps/v1
kind: Deployment
metadata:
  # {{KUBEDEV_DEPLOYMENT_NAME}}와 같은 변수(placeholder)는
  # 컨트롤러가 실제 리소스를 생성할 때 동적으로 값을 채워넣습니다.
  # 예: "user-dave-project-x-deployment"
  name: "{{KUBEDEV_DEPLOYMENT_NAME}}"
  labels:
    app: "{{KUBEDEV_APP_LABEL}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{KUBEDEV_APP_LABEL}}"
  template:
    metadata:
      labels:
        app: "{{KUBEDEV_APP_LABEL}}"
    spec:
      # initContainers: 메인 컨테이너가 시작되기 전에 먼저 실행되는 컨테이너입니다.
      # Git 리포지토리를 클론하는 용도로 완벽합니다.
      initContainers:
        - name: git-clone
          image: alpine/git # Git이 설치된 가벼운 이미지
          args:
            - clone
            - --single-branch
            - "https://github.com/vercel/next.js" # CRD의 spec.gitRepository 값으로 채워짐
            - /workspace # 클론받을 경로
          volumeMounts:
            - name: workspace-storage
              mountPath: /workspace
      containers:
        - name: web-ide-container
          # image: VS Code 웹 IDE가 설치된 도커 이미지입니다.
          # 여기에 Python, Node.js 등 필요한 런타임을 추가한 커스텀 이미지를 사용할 수 있습니다.
          image: codercom/code-server:latest
          args:
            - "--auth"
            - "none" # 인증 없이 바로 IDE 접속 (개발용)
            - "--bind-addr"
            - "0.0.0.0:8080"
            - "/workspace" # IDE 시작 시 열릴 기본 폴더 (git-clone이 완료된 폴더)
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: workspace-storage
              # /workspace 경로에 workspace-storage 볼륨을 연결합니다.
              # 이 폴더의 내용은 Pod가 재시작되어도 보존됩니다.
              mountPath: /workspace
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
      volumes:
        - name: workspace-storage
          persistentVolumeClaim:
            # claimName은 컨트롤러가 사용자별로 고유하게 생성할 PVC의 이름입니다.
            claimName: "{{KUBEDEV_PVC_NAME}}"
