# 시연용 간단한 Bash 스크립트 데모
# 실제 작동하는 init 명령 검증용
apiVersion: kubedev.my-project.com/v1alpha1
kind: KubeDevEnvironment
metadata:
  name: demo-bash-simple
  namespace: kubdev-users
spec:
  userName: "demo-student"
  gitRepository: "https://github.com/octocat/Hello-World.git"
  gitRef: "master"
  image: "codercom/code-server:latest"

  commands:
    init: |
      echo "========================================="
      echo "KubeDev 환경 초기화 시작"
      echo "========================================="
      echo ""
      echo "시스템 정보:"
      echo "  hostname: $(hostname)"
      echo "  user: $(whoami)"
      echo "  pwd: $(pwd)"
      echo ""
      echo "설치된 도구:"
      echo "  Git: $(git --version)"
      echo "  Bash: $BASH_VERSION"
      echo ""
      cd /workspace
      echo "워크스페이스 내용:"
      ls -lah
      echo ""
      if [ -d .git ]; then
        echo "Git 레포지토리 정보:"
        echo "  branch: $(git branch --show-current 2>/dev/null || echo 'main')"
        echo "  remote: $(git remote get-url origin 2>/dev/null || echo 'N/A')"
      fi
      echo ""
      echo "데모 파일 생성..."
      echo "# Welcome to KubeDev!" > /workspace/WELCOME.md
      echo "This environment was automatically created." >> /workspace/WELCOME.md
      echo "  Done!"
      echo ""
      echo "========================================="
      echo "환경 초기화 완료!"
      echo "========================================="

    start: ""

  ports:
    - 8080

  storage:
    size: "5Gi"
