apiVersion: kubedev.my-project.com/v1alpha1
kind: KubeDevEnvironment
metadata:
  name: demo-nodejs-working
  namespace: kubdev-users
spec:
  userName: "demo-student"
  gitRepository: "https://github.com/nodejs/nodejs.org.git"
  gitRef: "main"

  # Node.js í¬í•¨ëœ ì´ë¯¸ì§€ ì‚¬ìš©!
  image: "node:20-bookworm"
  
  commands:
    init: |
      echo "================================"
      echo "Node.js í™˜ê²½ ì„¤ì • ì‹œìž‘..."
      echo "================================"
      
      cd /workspace
      
      # Node.js ë²„ì „ í™•ì¸
      echo "âœ… Node.js: $(node --version)"
      echo "âœ… npm: $(npm --version)"
      
      # ê°„ë‹¨í•œ í”„ë¡œì íŠ¸ ìƒì„±
      cat > package.json << 'PKGJSON'
      {
        "name": "kubedev-demo",
        "version": "1.0.0",
        "scripts": {
          "start": "node server.js"
        },
        "dependencies": {
          "express": "^4.18.2"
        }
      }
      PKGJSON
      
      # Express.js ì„¤ì¹˜
      echo "ðŸ“¦ Express ì„¤ì¹˜ ì¤‘..."
      npm install
      
      # ê°„ë‹¨í•œ ì„œë²„ ìƒì„±
      cat > server.js << 'SERVERJS'
      const express = require('express');
      const app = express();

      app.get('/', (req, res) => {
        res.send('<h1>Hello from KubeDev!</h1>');
      });

      app.listen(3000, () => {
        console.log('Server running on port 3000');
      });
      SERVERJS
      
      echo ""
      echo "âœ… í™˜ê²½ ì„¤ì • ì™„ë£Œ!"
      echo "================================"
    
    start: ""
  
  ports:
    - 8080  # code-server
    - 3000  # Express app

  storage:
    size: "5Gi"
