apiVersion: kubedev.my-project.com/v1alpha1
kind: KubeDevEnvironment
metadata:
  name: test-manual-env
  namespace: kubdev-users
spec:
  userName: "testuser"
  gitRepository: "https://github.com/example/repo.git"
  gitRef: "main"
  template:
    apiVersion: apps/v1
    kind: Deployment
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: test
              image: busybox
              command: ["sleep", "3600"]
